// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// bootstrap_mean_diffs
Rcpp::NumericVector bootstrap_mean_diffs(Rcpp::NumericVector vals, Rcpp::IntegerVector grps, int B, int fixed_seed);
RcppExport SEXP _hrqolr_bootstrap_mean_diffs(SEXP valsSEXP, SEXP grpsSEXP, SEXP BSEXP, SEXP fixed_seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type vals(valsSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type grps(grpsSEXP);
    Rcpp::traits::input_parameter< int >::type B(BSEXP);
    Rcpp::traits::input_parameter< int >::type fixed_seed(fixed_seedSEXP);
    rcpp_result_gen = Rcpp::wrap(bootstrap_mean_diffs(vals, grps, B, fixed_seed));
    return rcpp_result_gen;
END_RCPP
}
// fast_auc
Rcpp::NumericVector fast_auc(Rcpp::NumericVector x, Rcpp::NumericVector y);
RcppExport SEXP _hrqolr_fast_auc(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(fast_auc(x, y));
    return rcpp_result_gen;
END_RCPP
}
// linear_approx
std::vector<double> linear_approx(std::vector<double> x, std::vector<double> y, std::vector<double> xout);
RcppExport SEXP _hrqolr_linear_approx(SEXP xSEXP, SEXP ySEXP, SEXP xoutSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<double> >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type y(ySEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type xout(xoutSEXP);
    rcpp_result_gen = Rcpp::wrap(linear_approx(x, y, xout));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_hrqolr_bootstrap_mean_diffs", (DL_FUNC) &_hrqolr_bootstrap_mean_diffs, 4},
    {"_hrqolr_fast_auc", (DL_FUNC) &_hrqolr_fast_auc, 2},
    {"_hrqolr_linear_approx", (DL_FUNC) &_hrqolr_linear_approx, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_hrqolr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
