# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Bootstrap mean differences
#'
#' @param vals numeric vector of values from observations
#' @param grps int vector with group assignments of the values in the `vals` parameter.
#' 	Assumes: 0 = actv, 1 = ctrl.
#' @param B int, the number of bootstrap samples (default = 2000)
#' @param fixed_seed int, seed to be used for pseudo-random number generation
#'
#' @return bootstrap samples of the mean difference by group assignment, as numeric vector.
#'
#' @export
bootstrap_mean_diffs <- function(vals, grps, B = 2000L, fixed_seed = 4131L) {
    .Call(`_hrqolr_bootstrap_mean_diffs`, vals, grps, B, fixed_seed)
}

