# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Bootstrap mean differences
#'
#' @param vals numeric vector of values from observations
#' @param grps int vector with group assignments of the values in the `vals` parameter.
#' 	Assumes: 0 = actv, 1 = ctrl.
#' @param B int, the number of bootstrap samples (default = 2000)
#' @param fixed_seed int, seed to be used for pseudo-random number generation
#'
#' @return bootstrap samples of the mean difference by group assignment, as numeric vector.
#'
#' @export
bootstrap_mean_diffs <- function(vals, grps, B = 2000L, fixed_seed = 4131L) {
    .Call(`_hrqolr_bootstrap_mean_diffs`, vals, grps, B, fixed_seed)
}

#'
NULL

#' Interpolate multiple values
#'
#' User-facing, stripped-down version of approx.c from the stats package (which is around twice
#' as fast as this one).
#' Yields somewhere around 10x speed-up compared to using stats::approx().
#'
#' @param x,y coordinates for known observationa
#' @param xout vector or scalar with value(s) where interpolation should happen
#'
#' @return Interpolated values
#' @export
#'
linear_approx <- function(x, y, xout) {
    .Call(`_hrqolr_linear_approx`, x, y, xout)
}

